server {
    listen 80;
    listen [::]:80;
    server_name guthib.org www.guthib.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name guthib.org www.guthib.org;

    root /var/www/guthib;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/guthib.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/guthib.org/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /api/guestbook/ {
        proxy_pass http://127.0.0.1:3847/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
